### ISSUE TITLE
Free disk space checks attempted even when using only a watch directory

### ISSUE THREAD

**Issue by rcedwards** [s0up4200/ptparchiver-go#23]
It looks like the qBittorrent free disk space check is occurring even when you don't have a qBittorrent client configured.

Conifg:

```yaml
# PTP API credentials
apiKey: XXX
apiUser: XXX
baseUrl: https://passthepopcorn.me

# Define archive containers
containers:
  watch-container:
    size: 200G # Total storage allocation
    watchDir: /archive/intake # Directory to save .torrent files to

fetchSleep: 120 # Seconds between API requests, do not set lower than 5 unless you want to get banned
interval: 360 # Minutes between fetch attempts when running as a service (default: 6 hours)
```

Error
```
2025-03-15T16:38:34Z INF skipping fetch due to insufficient disk space container=watch-container freeSpace=0B requiredSpace=37.39GB torrentName=example
```
